### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by samuelecalamita** [ifahrentholz/eds-editorial#36]
we need an error handling strategy for the fetch requests

**Comment by mabrinasueller** [comment]
I implemented error handling in the project for all components taht use fetchService. There are still 2 things that need to be done: 
1. in sidebarPosts.ts line 51, the string for the placeholder is not getting resolved correctly if there are no posts yet  (but no error)
2. There still needs to be a solution implemented for missing stylesheets in main.service.ts for loadCSS(). There is still an error message in the  console if a component has no stylesheet
