### ISSUE TITLE
Fixing side navigation listing all entrys

### ISSUE THREAD

**Issue by LoomingEcho** [ifahrentholz/eds-editorial#42]
Currently, all drive directories/docs will appear in the navigation. Find a way to utilize something like a blacklist to prevent listing them in the navigation.

### Nav notes which should be hidden are: 
1. Development
2. Sidekick-Library -> talk to Elanor and check if this site-note has to be unpublished or if we have to remove it via code
3. Sidekick
4. Tools

**Comment by ifahrentholz** [comment]
Dupes: #43
